### ISSUE TITLE
Artifacts with vector path in example template

### ISSUE THREAD

**Issue by Tapped** [fusetools/fuselibs-public#1078]
Verified to be an issue in 6869d2b3c2 and 818550fd5dc42c78ba19d98b97d6a072fa885fec
Only tested on Windows

Steps to reproduce:
1. `Stuff/uno build -t=dotnet -r -l ProjectTemplates/Projects/Example/`
2. Navigate to the last page

![image](https://user-images.githubusercontent.com/1014854/37102960-6ac24814-2229-11e8-9e0f-85126874db20.png)

**Comment by mortoray** [comment]
This Path has an invalid final bit to it `...M -1.0 -10.0 l 1,1 z"`  That moves to -1,-10 does a line to 1,1, and then closes the figure. I suppose that shouldn't render anything, but that might be hard to detect such invalid shapes.

**Comment by mortoray** [comment]
![screenshot_20180312_075014](https://user-images.githubusercontent.com/1308999/37269289-0c0b6cd4-25ca-11e8-8d95-630f7b66ae5d.png)

This is a capture from Inkscape, notice the odd bit in the top-left. It does render differently though, so perhaps still technically a defect in fuselibs.

**Comment by mortoray** [comment]
DotNet doesn't appear to have a function that supports this correctly. It has only `CloseFigure` which draws a straight connecting line, which is what we are seeing. SVG allows a move command to "end" the current figure without drawing a line. DotNet is closing to the bototm-right graphic on that final close command.

In the SVG file, that bottom-right graphic, the top-left corner, draws without a completing path. There are two end-points instead of a complete curve.

**Comment by mortoray** [comment]
StartFigure/CloseFigure also draws the connecting line.

In order to support the correct SVG drawing here we'd need to create two paths: One for the filling and one for the strokes. The filled path would require use calling `StartFigure` and `CloseFigure`. The stroked path would not want that -- since we could be animating lines.  Unfortunately System.Drawing has no support for ending a segment without adding a connecting line.

**Comment by Tapped** [comment]
It's a regression though, since the line wasn't visible in fuselibs version `1.7`.
