### ISSUE TITLE
Example template reports: `A grid is using incompatible layout parameters[...]`

### ISSUE THREAD

**Issue by Tapped** [fusetools/fuselibs-public#1127]
This diagnostic message here https://github.com/fusetools/fuselibs-public/blob/27c7adf5bef14f909e154cdba12b88931fbd5cab/Source/Fuse.Controls.Panels/Layouts/GridLayout.uno#L1014 is reported when running https://github.com/fusetools/fuselibs-public/blob/master/ProjectTemplates/Projects/Example/

Also I'm not sure this should be reported as an error, since it's a common thing to do and was working fine before. In my opinion this should be counted as a warning instead. 

## Steps to reproduce
1. Open `Fuse Studio`, and click create new example application.
2. Navigate to the last page of the example project
3. Notice that a problem is reported under the problems tab

**Comment by mortoray** [comment]
There were some small issues fixed in layout recently... has this been checked against master?   The issues weren't with `Grid` itself, but with `StackPanel` and `DockPanel`, requesting an invalid sizing mode of the `Grid`, and thus generating this message.

It's an error because the `GridLayout` has actually detected an error (this isn't a heuristic and/or property check). It tracks certain layout conditions to detect that you've entered a mode it is known to produce the wrong and inconsistent sizes for.  The grid in this example should work though, which means it's likely the aforementioned problem.

**Comment by mortoray** [comment]
This was the issue where I fixed part of the problem: https://github.com/fusetools/fuselibs-public/issues/1082

**Comment by mortoray** [comment]
I tested the code on master and it doesn't produce any errors (looking at it, I'm sure there's another recent issue I fixed related to it as well).
