### ISSUE TITLE
NavigateToggle does not locate the appropriate Navigation context

### ISSUE THREAD

**Issue by COCPORN** [fusetools/fuselibs-public#226]
Find attached a "minimal" reproduction of the issue.

I am not sure whether this is related to `ux:Dependency` or it is an issue with the `EdgeNavigator` and `NavigateToggle`.

Expected behavior:

- Both clicking the red square and the center button should toggle the edge menu

Actual behavior:

- Clicking the red square toggles the edge menu
- Clicking the center button _does nothing_

[DependencyRepro.zip](https://github.com/fusetools/fuselibs-public/files/1152355/DependencyRepro.zip)

**Comment by mortoray** [comment]
`Target` here is the target page for `NavigateToggle`, but you also need to specify the navigation context. With `EdgeNavigator` this is a bit tricky since it isn't a navigation object itself.  But, if  really needed you can do:

                    <MainContent ux:Template="mainContent" sideMenu="sideMenu" edgeNav="edgeNav" />

And then:

```
<Page ux:Class="MainContent">
    <SideMenu ux:Dependency="sideMenu" />
    <EdgeNavigator ux:Dependency="edgeNav" />

    <Button Text="Show menu" Navigation="{Property edgeNav.Navigation}">
        <Clicked>
            <NavigateToggle Target="sideMenu" />
        </Clicked>
    </Button>

</Page>
```

It's possible to put the context directly on the toggle as well:

            <NavigateToggle  NavigationContext="{Property edgeNav.Navigation}" Target="sideMenu" />


This issue is now for making the navigation context implicit if a Target page is provided. Though I'm uncertain of priority since I don't think this is a good way to do things. I find it much cleaner to expose a `Open`, `Toggle` or `Close` `UserEvent` that do this. The lower-level UX shouldn't be so tightly bound to the high-level objects.

**Comment by mortoray** [comment]
This issue is likely part of a bigger EdgeNavigator cleanup. It suffers from many small problems now. Search the old issue system.

**Comment by kristianhasselknippe** [comment]
@mortoray: Could NavigateToggle just use the navigation context of the element it is working on?

**Comment by mortoray** [comment]
@kristianhasselknippe Yes, that's why I'm leaving this issue open as a defect. The context can be easily determined from the target page.
