### ISSUE TITLE
multi-line text does not draw an ellipsis

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#484]
Fuse 1.2.1 build 13974, macOS.

Affected: tested on Android 6, but iOS is reported to be the same.

Repro:
```
<App Background="#000">
    <Text TextWrapping="Wrap" TextColor="#fff" ClipToBounds="true" Width="240" Height="80" Background="#fff4">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus elit non commodo suscipit. Sed a dui non leo mollis dictum. Integer tincidunt dapibus sollicitudin.
    </Text>
</App>
```
Expectation is to see ellipsis added at the end of 4th line, but it isn't there.

An ellipsis is added at the end of the first line if we remove `TextWrapping="Wrap"` from the `Text` element.

**Comment by kusma** [comment]
@eksperts: This is simply because the native renderers don't do this. We're just forwarding their behavior. I doubt we'll change this.

**Comment by ruudvanham** [comment]
@kusma Is there another way or a workaround to achieve this desired effect?

**Comment by kusma** [comment]
@ruudvanham: I'm not really aware, not. Perhaps -DUSE_HARFBUZZ will behave differently?

By the way, this limitation is the reason why we have `TextTruncation.Standard` rather than `TextTruncation.Ellipsis`. We're not making a promise to insert ellipses, as it would require us to do the actual text-layout (which we currently delegate to the native UI engine).

**Comment by kusma** [comment]
I don't think we're going to do anything about this.
