### ISSUE TITLE
Date and Time pickers crash Android 8 on touch

### ISSUE THREAD

**Issue by Sunjammer** [fusetools/fuselibs-public#764]
Fuse 1.4 public, any interaction with a DatePicker or TimePicker hangs the app interminably on my Pixel w. Android 8

**Comment by yupferris** [comment]
On @kusma's test device, I'm also getting very strange layout/crash bugs. I wonder how much of this is at all robust with Android 8. Needs lots of testing and some test projects outside of Fuse to see what's going on.

**Comment by fusebuild** [comment]
The forum thread [App getting crash after selecting date in DatePicker](https://www.fusetools.com/community/forums/bug_reports/app_getting_crash_after_selecting_date_in_datepick) posted by Dhvl Golakiya was linked to this issue.

**Comment by yupferris** [comment]
User reports also crashing on iPhone 6s. This may be caused by property feedback loops.

**Comment by yupferris** [comment]
Ok, so I can get this to break on interaction in fuse preview, but not regular builds, which probably explains why I hadn't seen this before. I need to investigate further to see if this happens on Windows (I've only got it to break so far on mac).

**Comment by yupferris** [comment]
Ok yeah, this breaks in Android preview with the latest fuse release on Windows. I'll see if a local Fuse build on top of latest uno/fuselibs is any different.

**Comment by yupferris** [comment]
Breaks on local builds on all 1.4 branches, time to mix/match/debug :)

**Comment by yupferris** [comment]
It seems to be related to databinding with `Value`; it's possible this is propagation loops again, but I'm not sure, and it's probably not the same bug I fixed when fixing the properties.

**Comment by yupferris** [comment]
After more thorough investigation, it appears this is actually an issue with marshaling `Uno.DateTime`/`Date` between uno/js. I've got a minimal repro case that breaks in the same way just with this kind of databinding and nothing to do at all with the pickers (other than the fact that they obviously databind with the same types). I still don't really know why this breaks though.

**Comment by yupferris** [comment]
I've tried several things to further isolate this (to no avail), including:
- Round-tripping `DateTime`/`Date` objects to/from JS
- Passing `DateTime` objects (both wrapped and unwrapped since `DateTime` is a struct) between threads
- Replacing the .ux code with the .uno code generated by the UX compiler

The last bit is particularly interesting because it means the issue is probably lurking in the property/binding objects that the simulator generates, although those are a bit more difficult to dig into. This of course matches a normal uno build structurally, the difference being that it executes within the simulator in this case. Either that or I'm still way off. But I think it's very likely now that the issue lies in the simulator.
