### ISSUE TITLE
Model is pre-evaluating `get` accessors, making recursive structures impossible

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#849]
It's not possible to create a recursive model structure with accessors. It appears they are evaluated immediately instead of on demand as expected. 

```
export default class Main {
	constructor() {
		this.data = new Data(0)
	}
}

class Data {
	constructor(id) {
		this.id = id
	}
	
	get nextData() {
		console.log( "NextData: " + this.id )
		return new Data(this.id + 1)
	}
}
```

Even when not used, such as `<App Model="Main"></App>` this accessor is called.

**Comment by mortoray** [comment]
This type of setup had two common use-cases:

- To have a preview next/prev item in a display of items. This can be done with a `<With Data="{nextData}">...</With>` setup
- To provide declarative navigation such as `<GotoRoute Path="{nextRoute}"/>`. This is evaluated on demand by the `GotoRoute` action.

**Comment by mortoray** [comment]
One option here is to find a way to expose functions with return values to the UX bindings. So instead of `Path="{nextMonth}"` I'd have `Path="{getNextMonth()}"`.

**Comment by Duckers** [comment]
Getters are eagerly evaluated. This is by design, and should not be changed. This is critical to allow things like time-travel-debugging and analytics in the future, keeping the binding complexity down and prevent asynchronous "waiting for data"-scenarios in the UI.

If this is a real problem, then some sort of lambda syntax that allows the target property to lazily evaluate the expression is one option. Alternatively, make the property accept an expression, and lazily subscribe to it to get the value on demand.

**Comment by Duckers** [comment]
Also, I'd say in such scenarios where you generate a data structure for the next/previous pages etc, the following holds: The data structures that you generate should be pure, intert values. Creating them should have no side effects.

**Comment by mortoray** [comment]
The created data structures are "inert" in that sense. They are pure data, except they have in truen the `next` structure as well, which is evaluated to infinity then.

I think a function call syntax at the UX level would alleviate the problem `Value="{getValue()}"`

**Comment by mortoray** [comment]
Closing in favour of implementing https://github.com/fusetools/fuselibs-public/issues/856
